config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rent_items, only: %i[index show]
  devise_for :users
  get "/home", to: "pages#home"
  get "/about", to: "pages#about"
  post "/create_contact", to: 'pages#create_contact'
  root to: "pages#home"

  resources :rent_items, only: %i[index show create edit update destroy]
  resources :image_elements, only: %i[index create update destroy]

  namespace :dashboard do
    resources :rent_items
    resources :rent_requests, only: %i[index create update]
    root to: 'dashboard#home'
  end
end

app/models/rent_item.rb
# frozen_string_literal: true

class RentItem < ApplicationRecord
  belongs_to :user
  has_many :rent_requests, dependent: :destroy
  has_many :image_elements, dependent: :destroy

  validates :location, :condition, :item_type, presence: true
  validates :item_type, presence: true, if: :item_type_valid?

  def item_type_valid?
    ITEM_TYPES.include?(item_type)
  end

  scope :rent_item_per_type, ->(rent_type) { where(item_type: rent_type) }
  scope :my_rentals, ->(logged_user) { where(user_id: logged_user) }
  scope :not_my_rentals, ->(current_user) { where.not(user_id: current_user) }
  scope :available_rentals, -> { where(available: true) }
end

app/controllers/dashboard/dashboard_controller.rb
# frozen_string_literal: true

module Dashboard
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    before_action :rents, only: %i[home]

    layout 'dashboard'

    def home
      @count_rent = current_user.rent_items.size
    end

    private

    def rents
      @rented_type = current_user.rent_items.pluck(:item_type)
      @rented_types = current_user.rent_items.pluck(:for_age)
    end
  end
end

app/controllers/dashboard/rent_items_controller.rb
# frozen_string_literal: true

module Dashboard
  class RentItemsController < Dashboard::DashboardController
    include Pagy::Backend

    before_action :find_rent_item, only: %i[show edit update]
    before_action :rent_item_authorization, only: %i[show edit update destroy]

    def index
      @pagy, @rent_items = pagy(current_user.rent_items)
      authorize @rent_items
    end

    def show; end

    def new
      @rent_item = RentItem.new
      authorize @rent_item
    end

    def create
      @rent_item = RentItem.new(rent_item_params)
      @rent_item.user_id = current_user.id
      authorize @rent_item
      if @rent_item.save
        redirect_to @rent_item, notice: 'Rent Item has been successfully created!'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @rent_item.update(rent_item_params)
        redirect_to dashboard_rent_items_path, notice: 'Rent Item has been updated!'
      else
        render :edit
      end
    end

    def destroy
      @rent_item.destroy

      redirect_to rent_items_path
    end

    private

    def rent_item_params
      params.require(:rent_item).permit(:condition, :for_age, :item_type, :location, :available)
    end

    def find_rent_item
      @rent_item = RentItem.my_rentals(current_user).first
    end

    def rent_item_authorization
      authorize @rent_item
    end
  end
end

app/controllers/dashboard/rent_requests_controller.rb
# frozen_string_literal: true

module Dashboard
  class RentRequestsController < Dashboard::DashboardController
    include Pagy::Backend
    before_action :find_rent_request, only: %i[update]

    def index
      current_user_rent_items = current_user.rent_items.pluck(:id)
      @pagy, @rent_requests = pagy(RentRequest.where(rent_item_id: current_user_rent_items).pending)
      authorize @rent_requests
    end

    def create
      @rent_request = RentRequest.new(create_rent_request_params)
      @rent_request.user_id = current_user.id
      authorize @rent_request
      if @rent_request.save
        redirect_to rent_items_path, notice: 'Succesfully requested a Rent'
      else
        redirect_to root_path, alert: 'There was a problem, please try again'
      end
    end

    def update # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
      authorize @rent_request
      if @rent_request.update(update_rent_request_params)
        if @rent_request.accepted?
          @rent_request.rent_item.update(available: false)
          reject_pending_requests(@rent_request)
          ApproveMailer.new_approve(@rent_request).deliver_now
        end

        if @rent_request.rejected?
          @rent_request.rent_item.update(available: true)
          RejectMailer.reject_email(@rent_request).deliver_now
        end

        redirect_to dashboard_rent_requests_path, notice: 'Rent Request successfully updated'
      else
        redirect_to dashboard_rent_requests_path, alert: 'Rent Request was not updated'
      end
    end

    private

    def create_rent_request_params
      params.require(:rent_request).permit(:rent_item_id)
    end

    def update_rent_request_params
      params.require(:rent_request).permit(:status)
    end

    def find_rent_request
      @rent_request = RentRequest.find(params[:id])
    end

    def reject_pending_requests(rent_request)
      RentRequest.where(rent_item_id: rent_request.rent_item.id).pending.each do |rr|
        rr.reject!
        RejectMailer.reject_email(rr).deliver_now
      end
    end
  end
end

app/controllers/rent_items_controller.rb
# frozen_string_literal: true

class RentItemsController < ApplicationController
  before_action :scope_rent_items, only: :index
  include Pagy::Backend

  def index
    @pagy, @rent_items = pagy(@rent_items)
  end

  def show
    @rent_item = RentItem.find(params[:id])
  end

  private

  def scope_rent_items
    @rent_items = if params[:rent_type]
                    RentItem.not_my_rentals(current_user).available_rentals.rent_item_per_type(params[:rent_type])
                  else
                    RentItem.not_my_rentals(current_user).available_rentals.order(created_at: :desc)
                  end
  end
end

app/views/dashboard/rent_items/_form.html.erb
<div class="h-screen md:grid md:items-center px-8 md:px-80 ">
    <section class="max-w-4xl p-6 mx-auto bg-white rounded-md shadow-md dark:bg-gray-800">
        <%= form_with model: [:dashboard, @rent_item] do |f|%>
                <div class="grid grid-cols-1 gap-6 mt-4  lg:grid-cols-2">
                    <div class= 'border-t-2 border-green-500 border-rounded rounded-t'>
                        <%= f.label :item_type, class:"text-gray-700 dark:text-gray-200 bg-opacity-2 border-b-2 bg-opacity-5 border-green-600 rounded-b" %>
                        <%= f.select :item_type, ITEM_TYPES, class:"block w-full px-4 py-2 mt-2 text-gray-700 bg-white rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-green-500 dark:focus:border-blue-500" %>
                    </div>

                    <div class= 'border-t-2 border-green-500 border-rounded rounded-t'>
                        <%= f.label :condition, class:"text-gray-700 dark:text-gray-200 focus:outline-none border-b-2 bg-opacity-5 border-green-600 rounded-b" %>
                        <%= f.select :condition, CONDITIONS, class:"block w-full px-4 py-2 mt-2 text-gray-700 bg-gray-300 border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring" %>
                    </div>

                    <div class= 'border-t-2 border-green-500 border-rounded rounded-t'>
                        <%= f.label :location, class:"text-gray-700 dark:text-gray-200 border-b-2 bg-opacity-5 border-green-600 rounded-b" %>
                        <%= f.text_field :location, id:"location", type:"text", class:"block w-full px-4 py-2 mt-2 text-gray-700 bg-gray-100 hover:bg-gray-200 border rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-green-500 dark:focus:border-green-500 focus:outline-none ", placeholder: 'Your Location' %>
                    </div>

                    <div class= 'border-t-2 border-green-500 border-rounded rounded-t'>
                        <%= f.label :for_age, class:"text-gray-700 dark:text-gray-200 border-b-2 bg-opacity-5 border-green-600 rounded-b " %>
                        <%= f.select :for_age, FOR_AGES, class:"block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring" %>
                    </div>

                    <div class= "flex flex-row mt-4 border-green-500 border-rounded rounded-t">
                        <%= f.label :available, class:"text-gray-700 dark:text-gray-200  border-b-2 bg-opacity-5 border-green-600 rounded-b" %>
                        <%= f.check_box :available, class:"block w-full px-4 py-2 mt-2 text-gray-700 bg-gray-100 border border-gray-300 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring" %>
                    </div>
                </div>

                    <div class="flex items-end mt-12 w-4/12 space-x-3 ">
                        <%= f.submit class:"uppercase text-sm font-bold bg-green-600 text-gray-100 p-3 rounded-lg focus:shadow-outline transition-colors duration-200 hover:bg-green-700 dark:hover:bg-gray-200" %>
                        <%= link_to t('.cancel'), dashboard_rent_items_path, class:"uppercase  text-sm font-bold bg-green-600 text-gray-100 p-3 rounded-lg  focus:shadow-outline transition-colors duration-200  hover:bg-green-700 dark:hover:bg-gray-200" %>
                    </div >
            </div>
        <% end %>
    </section>
</div>

app/views/dashboard/rent_items/edit.html.erb
<div class="heading text-center font-bold text-2xl m-5 text-gray-100"> <%= t('.edit')%> </div>

<%= render 'form' %>

app/views/dashboard/rent_items/index.html.erb
<div class="flex flex-col items-center">
    <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 pl-2 pr-2 py-6">
        <% @rent_items.each do |rent_item| %>
            <div class="flex max-w-sm mx-5 mt-8 overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800 sm:text-center">
                <img class="object-cover hidden sm:block object-center w-1/2 h-56" src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" alt="avatar">
                <div class=" px-6 py-4">
                    <p class="text-xl font-semibold text-gray-800 dark:text-white">
                        <%= link_to  rent_item.item_type.capitalize, rent_item%>
                    </p>

                    <p class="py-2 text-gray-700 border-t-2 dark:text-gray-400"> <%= t('.best_for')%>:
                    <%=link_to rent_item.for_age, rent_item%>
                    </p>
                    <p class="py-2 text-gray-700 border-t-2 dark:text-gray-400"> <%= t('.status')%>
                        <% if rent_item.available%>
                        <p class="text-green-500"> <%= t('.for_rent')%></p>
                        <% else %>
                        <p class="text-red-500"> <%= t('.taken')%></p>
                        <% end %>
                    </p>
                        <%=link_to "View Pictures", '#', class:'md:hidden lg:hidden py-1 text-sm underline'%>
                    <div class="flex items-center object-contain md:object-scale-down mt-4 text-gray-700 dark:text-gray-200">
                        <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M14 11H10V13H14V11Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M7 5V4C7 2.89545 7.89539 2 9 2H15C16.1046 2 17 2.89545 17 4V5H20C21.6569 5 23 6.34314 23 8V18C23 19.6569 21.6569 21 20 21H4C2.34314 21 1 19.6569 1 18V8C1 6.34314 2.34314 5 4 5H7ZM9 4H15V5H9V4ZM4 7C3.44775 7 3 7.44769 3 8V14H21V8C21 7.44769 20.5522 7 20 7H4ZM3 18V16H21V18C21 18.5523 20.5522 19 20 19H4C3.44775 19 3 18.5523 3 18Z"/>
                        </svg>

                        <h1 class="px-2 text-sm"><%=link_to rent_item.condition, rent_item%></h1>
                    </div>

                    <div class="flex items-center md:place-items-center mt-4 text-gray-700 dark:text-gray-200">
                        <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M16.2721 10.2721C16.2721 12.4813 14.4813 14.2721 12.2721 14.2721C10.063 14.2721 8.27214 12.4813 8.27214 10.2721C8.27214 8.063 10.063 6.27214 12.2721 6.27214C14.4813 6.27214 16.2721 8.063 16.2721 10.2721ZM14.2721 10.2721C14.2721 11.3767 13.3767 12.2721 12.2721 12.2721C11.1676 12.2721 10.2721 11.3767 10.2721 10.2721C10.2721 9.16757 11.1676 8.27214 12.2721 8.27214C13.3767 8.27214 14.2721 9.16757 14.2721 10.2721Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M5.79417 16.5183C2.19424 13.0909 2.05438 7.3941 5.48178 3.79418C8.90918 0.194258 14.6059 0.0543983 18.2059 3.48179C21.8058 6.90919 21.9457 12.606 18.5183 16.2059L12.3124 22.7241L5.79417 16.5183ZM17.0698 14.8268L12.243 19.8965L7.17324 15.0698C4.3733 12.404 4.26452 7.9732 6.93028 5.17326C9.59603 2.37332 14.0268 2.26454 16.8268 4.93029C19.6267 7.59604 19.7355 12.0269 17.0698 14.8268Z"/>
                        </svg>

                        <h1 class="px-2 text-sm">
                            <%= link_to rent_item.location, rent_item, class:"underline"%>
                        </h1>
                    </div>

                    <div class="flex items-center mt-4 text-gray-700 dark:text-gray-200">
                        <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M3.00977 5.83789C3.00977 5.28561 3.45748 4.83789 4.00977 4.83789H20C20.5523 4.83789 21 5.28561 21 5.83789V17.1621C21 18.2667 20.1046 19.1621 19 19.1621H5C3.89543 19.1621 3 18.2667 3 17.1621V6.16211C3 6.11449 3.00333 6.06765 3.00977 6.0218V5.83789ZM5 8.06165V17.1621H19V8.06199L14.1215 12.9405C12.9499 14.1121 11.0504 14.1121 9.87885 12.9405L5 8.06165ZM6.57232 6.80554H17.428L12.7073 11.5263C12.3168 11.9168 11.6836 11.9168 11.2931 11.5263L6.57232 6.80554Z"/>
                        </svg>
                        <h1 class="px-2 text-sm">
                            <%= mail_to rent_item.user.email, rent_item.user.email, class:"underline"%>
                        </h1>
                    </div>
                    <div class="mt-2">
                        <%= link_to  t('.edit'), edit_dashboard_rent_item_path(rent_item), class:"shadow"%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div>
        <%== pagy_nav(@pagy) unless @rent_items.empty? %>
    </div>
</div>

app/views/dashboard/rent_items/new.html.erb
<div class="heading text-center font-bold text-2xl m-5 text-gray-100 shaddow"> <%= t('.create')%> </div>

<%= render 'form'%>