config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rent_items, only: %i[index show]
  devise_for :users
  get "/home", to: "pages#home"
  get "/about", to: "pages#about"
  post "/create_contact", to: 'pages#create_contact'
  root to: "pages#home"

  resources :rent_items, only: %i[index show create edit update destroy]
  resources :image_elements, only: %i[index create update destroy]

  namespace :dashboard do
    resources :rent_items
    resources :rent_requests, only: %i[index create update]
    root to: 'dashboard#home'
  end
end

app/views/layouts/_flash.erb
<% flash.each do |type, msg| %>
<div data-controller="flash" data-flash-target="flashdisplay" class="text-white <%= type == 'notice' ? 'bg-green-600' : 'bg-red-500' %> ">
    <div class="container flex items-center justify-between px-6 py-2 mx-auto">
        <div class="flex">
            <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                <% case type %>
                <% when 'notice' %>
                    <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667 23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z"> </path> %>
                <% when 'alert' %>
                    <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"> </path>
                <% end %>
            </svg>
            <p class="mx-3"><%= msg %></p>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
<div data-controller="flash" data-flash-target="flashdisplay" class="text-white <%= type == 'notice' ? 'bg-green-600' : 'bg-red-500' %> ">
    <div class="container flex items-center justify-between px-6 py-2 mx-auto">
        <div class="flex">
            <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                <% case type %>
                <% when 'notice' %>
                    <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667 23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z"> </path> %>
                <% when 'alert' %>
                    <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"> </path>
                <% end %>
            </svg>
            <p class="mx-3"><%= msg %></p>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<nav data-controller="dropdown" class="bg-gray-100 shadow dark:bg-gray-800">
  <div  class="container px-6 py-4 mx-auto ">
    <div class="md:flex md:flex-row md:justify-between items-center">
      <div class="md:flex md:flex-row items-center">
          <div class="flex justify-between ">
            <!-- Logo-->
            <div class="text-xl font-semibold text-green-600">
              <%= link_to "RYDER", root_path, class:"text-2xl font-bold text-green-600 dark:text-white lg:text-3xl hover:text-green-700 dark:hover:text-gray-300"%>
            </div>
            <!-- Mobile menu button -->
            <div class="flex md:hidden">
              <button data-action="click->dropdown#hamburger" type="button" class="text-gray-500 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400 focus:outline-none focus:text-gray-600 dark:focus:text-gray-400" aria-label="toggle menu">
                <svg viewBox="0 0 24 24" class="w-6 h-6 fill-current">
                  <path fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                </svg>
              </button>
            </div>
          </div>
          <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
          <div data-dropdown-target="dropdown" class='sm:block'>
            <div class="flex flex-col md:flex-row md:items-center md:mx-8">
              <% if user_signed_in? %>
                <%= link_to t('.rentals'), rent_items_path, class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-800 dark:hover:bg-gray-300"%>
                <%= link_to t('.dashboard'), dashboard_root_path, class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-200 dark:hover:bg-gray-300"%>
                <%= link_to t('.about_us'), about_path,  class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-200 dark:hover:bg-gray-300"%>
                <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-200 dark:hover:bg-gray-300"%>
                <%= render 'layouts/i18n' %>
                <% else %>
                <%= link_to t('.log_in'), new_user_session_path, class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-200  dark:hover:bg-gray-300"%>
                <%= link_to t('.sign_up'), new_user_registration_path, class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-200dark:hover:bg-gray-300"%>
                <%= link_to t('.about_us'), about_path,  class:"px-2 py-1 mx-2 mt-2 text-sm font-medium text-gray-900 transition-colors duration-200 transform rounded-md md:mt-0 dark:text-gray-200  dark:hover:bg-gray-400"%>
                <%= render 'layouts/i18n' %>
              <% end %>
            </div>
          </div>
      </div>
      <!-- logged user ?-->
      <% if user_signed_in? %>
          <div class="hidden md:block mx-2 text-sm font-medium text-gray-900 dark:text-gray-200 justify-end transform rounded-md hover:bg-gray-400">
            <p><%=t('.logged_in_as')%>
                <%= current_user.first_name%> <%= current_user.last_name%>
            </p>
          </div>
          <div class="flex md:hidden items-center mt-4 md:mt-0">
            <button data-action="click->dropdown#hamburger" class="hidden mx-4 text-gray-600 md:block dark:text-gray-200 hover:text-gray-700 dark:hover:text-gray-200 focus:text-gray-700 dark:focus:text-gray-400 focus:outline-none" aria-label="show notifications">
            </button>
          </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_i18n.html.erb
<% I18n.available_locales.each do |l|%>
  <p class= 'hidden md:block'>|</p>
  <%= link_to l, url_for(locale: l.name), class:"font-medium text-gray-700"%>
  <p class= 'hidden md:block'>|</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ryder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ryder Dashboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- This needs to be fixed in rails way -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
        rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <!-- end of fixing the rails way -->
  </head>
    <body >
      <div class="flex h-full md:flex-row sm:h-full w-full lg:h-screen bg-gray-700" x-data="{openMenu:1}">
        <!--Start SideBar-->
          <aside class="w-20 relative z-20 flex-shrink-0 px-2 overflow-y-auto bg-green-600">
             <div class="mb-6">
                <!--Start NavItem -->
                <div>
                  <ul class=" mt-6 leading-10 px-4">
                    <li class="mb-3 p-2 rounded-md flex items-center justify-center bg-blue-400 cursor-pointer"
                        @click="openMenu !== 1 ? openMenu = 1 : openMenu = null">
                      <i class="fas fa-align-left fa-sm text-white"></i>
                    </li>
                    <%= link_to root_path  do %>
                      <li class="mb-3 p-2 rounded-md flex items-center justify-center bg-blue-200 cursor-pointer opacity-90">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                          <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                        </svg>
                      </li>
                    <% end %>
                    <%= link_to rent_items_path do%>
                      <li class="mb-3 p-2 rounded-md flex items-center justify-center bg-yellow-200 cursor-pointer">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                          <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z" />
                        </svg>
                      </li>
                    <% end %>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <li class="absolute bottom-0 mb-3 p-2 rounded-full flex items-start px-4 py-2 bg-gray-200 cursor-pointer">
                        <i class="fas fa-power-off fa-sm text-indigo-600"></i>
                      </li>
                    <% end %>
                  </ul>
                </div>
                <!--End NavItem -->
            </div>
        </aside>
        <!-- Start Open Menu -->
          <aside class="animate__animated animate__fadeInLeft w-52 relative z-0 flex-shrink-0 px-4 overflow-y-auto bg-gray-100 sm:block"
              x-show="openMenu ==  1"
              @click.away="openMenu = null"
              style="display: none;">
            <div class="mb-6">
              <!--Start Sidebar for open menu -->
              <div class="grid grid-cols-1 gap-4 mt-6">
                <!-- Start Navitem -->
                <%= link_to dashboard_root_path, class:'homepage-rent-type' do %>
                  <div class="rounded-full current-rent-type bg-gray-200 p-2  flex flex-col items-center">
                    <span class="fas fa-chart-pie fa-sm font-bold text-center"><%= t('.dashboard')%></span>
                  </div>
                <% end %>
                <!-- End Navitem -->
                <!-- Start Navitem -->
                <%= link_to edit_user_registration_path, class:'homepage-rent-type' do %>
                  <div class="rounded-full current-rent-type bg-gray-200 p-2  flex flex-col items-center">
                    <span class="fas fa-user-circle fa-sm font-bold text-center"><%= t('.account')%></span>
                  </div>
                <% end %>
                <!-- End Navitem -->
                <!-- Start Navitem -->
                <%= link_to new_dashboard_rent_item_path, class:'homepage-rent-type' do %>
                  <div class="rounded-full current-rent-type bg-gray-200 p-2  flex flex-col items-center">
                    <span class="fas fa-biking fa-sm font-bold text-center"><%= t('.new_rent')%></span>
                  </div>
                <% end %>
                <!-- End Navitem -->
                 <!-- Start Navitem -->
                <%= link_to dashboard_rent_items_path, class:'homepage-rent-type' do %>
                  <div class="rounded-full current-rent-type bg-gray-200 p-2  flex flex-col items-center">
                    <span class="fas fa-warehouse fa-sm font-bold text-center"><%= t('.my_rent')%></span>
                  </div>
                <% end %>
                <!-- End Navitem -->
                <!-- Start Navitem -->
                <%= link_to dashboard_rent_requests_path, class:'homepage-rent-type' do %>
                  <div class="rounded-full current-rent-type bg-gray-200 p-2  flex flex-col items-center">
                    <span class="fas fa-comment fa-sm font-bold text-center"><%= t('.view_request')%></span>
                  </div>
                <% end %>
                <!-- End Navitem -->
              </div>
              <!--End Sidebar for open menu -->
            </div>
          </aside>
        <!-- End Open Menu -->
        <!-- End Sidebar -->
          <div class="flex flex-col flex-1 w-full overflow-y-auto">
            <!--Start Topbar -->
            <!--End Topbar -->
            <main class="relative z-0 flex-1 pb-8 px-6 bg-gray-800">
              <div class="grid pb-10  mt-4 bg-gray-800 ">
                <%= render 'layouts/flash' %>
                <%= yield %>
              </div>
            </main>
          </div>
      </div>
    </body>
</html>